### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by juliocbcotta** [wongpiwat/flutter-trust-location#1]
Hey, it looks like there are a few missing dependencies to migrate to AndroidX libraries
https://github.com/wongpiwat/flutter-trust-location/blob/master/android/build.gradle#L38
It will break apps that write tests and depend on this plugin.

**Comment by wongpiwat** [comment]
@BugsBunnyBR,
Thank you for the information provided. I will fix it with the next release.
