### ISSUE TITLE
Please Migrate to Null-Safety

### ISSUE THREAD

**Issue by husainazkas** [wongpiwat/flutter-trust-location#11]
Hello, I'm very grateful with every contributors on this package. But, I hope the development of this package will continue and migrate to null-safety as soon as possible.

Thank You.

**Comment by fiiann** [comment]
Agree

**Comment by PongsiriTK** [comment]
will this plugin migrate null safety? or do we have any alternatives?

**Comment by wongpiwat** [comment]
Null safety migrated, please upgrade to new version `trust_location: ^2.0.12`
