### ISSUE TITLE
Different result every time app re-load

### ISSUE THREAD

**Issue by yusrenaltair** [wongpiwat/flutter-trust-location#5]
I tried your package and I haven't found a solution to deal with different results each time my application reloads with one call
```
await TrustLocation.isMockLocation
```
Trusted results can only be obtained by repeating as you write in the example folder. Are there other solutions to guarantee the results are correct without repeating by timer?

**Comment by wongpiwat** [comment]
@young-altair I have added stream getter where you can use this without coding a timer in your source code. Code example here. [trust_location](https://pub.dev/packages/trust_location)

**Comment by yusrenaltair** [comment]
Thanks a lot !

**Comment by yusrenaltair** [comment]
I am facing a new problem with the latest version.
I want to use a stream in another class but the following error appears
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Stream has already been listened to.
```
I changed the code as below
File : trust_location.dart
from
 ```
static var changeController = new StreamController<LatLongPosition>();
```
to
 ```
static var changeController = new StreamController<LatLongPosition>.broadcast();
```
Is this correct?

**Comment by wongpiwat** [comment]
@young-altair Correct. Thank you for suggestion. I will update it with next release.
